### ISSUE TITLE
Copyrighted material

### ISSUE THREAD

**Issue by nathancarter** [RishiSankineni/Data-Science-Books#1]
It looks like a lot of this material violates copyright law.  I think you need to take a lot of it down.  You can't post it publicly here unless you have a license to do so, otherwise it's violating the law.  If you do have a license to do so, make that clear somewhere in the repository.

**Comment by RishiSankineni** [comment]
@nathancarter  Oops, I'll take the content down at the earliest. Thanks, for letting me know.
